config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  #get 'top/index'
  # topページ追加
  root to: 'top#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # RESTful + search + csvを追加
  resources :customers do
        collection do
          get "search"
          get "csv_output"
          
          #csv
          
        end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    
    #admin以外読み取り
    can :read, :all

    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end



    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < ApplicationRecord
  
  # バリデーション 
  #validates :company, presence: true, length: { maximum: 255 }
  #validates :company2, presence: true, length: { maximum: 255 }
  #validates :company3, presence: true, length: { maximum: 255 }
  #validates :company4, presence: true, length: { maximum: 255 }
  #validates :phone, presence: true, length: { maximum: 255 }
  #validates :server, presence: true, length: { maximum: 255 }
  #validates :remark, presence: true, length: { maximum: 255 }

def self.search(search)
    #if search
       #Customer.where(['company LIKE ?', "%#{search}%"])
       #Customer.where(kind: 0).where(name: ‘yamada’)
        Customer.where(['company LIKE ?', "%#{search}%"])
    #else
      #Customer.all
    #end
end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # ログイン状態を判定
  #before_action :authenticated_user!
  #before_action :authenticate_user!
    
  protect_from_forgery with: :exception
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/customers/_form.html.erb
<!-- # パーシャル -->


 <!-- # バリデーション -->
 
    <% if customer.errors.any? %>
      <div id="error_explanation">
        <ul>
          <% customer.errors.full_messages.each do |customer| %>
            <li><%= customer %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    

app/views/customers/edit.html.erb
<%= render 'form', customer: @customers %>

<%= form_for(@customers) do |f| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><i class="#fa fa-search"></i> 会社編集</h3>
     </div>
       </div>
	<tbody>
	 <table class="table table-stripe table-bordere" >
		<tr>
			<td class="col-md-1"><%= f.label :company, "会社名" %></td>
 			<td class="col-md-3"><%= f.text_field :company %></td>
 			<td class="col-md-1"><%= f.label :vdc, "識別子" %></td>
 			<td class="col-md-2"><%= f.text_field :vdc %></td>
 			<td class="col-md-1"><%= f.label :contractdate, "契約日" %></td>
 			<td class="col-md-2"><%= f.text_field :contractdate %></td>
		</tr>
		<tr>
			<td class="col-md-"><%= f.label :server, "監視プロダクト" %></td>
			<td "col-md-"><%= f.text_field :server %></td>
			<td "col-md-"><%= f.label :monitoring, "監視方法" %></td>
			<td><%= f.text_field :monitoring %></td>
			<td "col-md-"><%= f.label :cancellationdate, "解約日" %></td>
			<td><%= f.text_field :cancellationdate %></td>
		</tr>
		<tr>
			<td><%= f.label :product, "利用サービス" %></td>
			<td><%= f.text_field :product %></td>
			<td><%= f.label :level, "対応レベル" %></td>
			<td><%= f.text_field :level %></td>
      <td></td>
      <td></td>
		</tr>

		<tr>
			<td><%= f.label :a, "監視" %></td>
			<td><%= f.label :a, "URL" %></td>
			<td><%= f.label :a, "認証情報" %></td>
			<td><%= f.label :a, "IPアドレス" %></td>
      <td><%= f.label :a, "root" %></td>
      <td><%= f.label :a, "識別子" %></td>
		</tr>
		<tr>
			<td><%= f.label :a, "内部" %></td>
			<td><%= f.text_field :link %></td>
			<td><%= f.text_field :auth %></td>
			<td><%= f.text_field :ipadd %></td>
      <td><%= f.text_field :root %></td>
      <td><%= f.text_field :vdc2 %></td>
		</tr>
		<tr>
			<td><%= f.label :a, "外部" %></td>
			<td><%= f.text_field :link2 %></td>
			<td><%= f.text_field :auth2 %></td>
			<td><%= f.text_field :ipadd2 %></td>
      <td><%= f.text_field :root2 %></td>
      <td><%= f.text_field :vdc3 %></td>
		</tr>
		
		<tr>
			<td><%= f.label :sheet, "登録シート" %></td>
			<td><%= f.text_field :sheet %></td>
			<td></td>
			<td></td>
      <td></td>
      <td></td>
		</tr>
		<tr>
			<td><%= f.label :deliverytime, "提供時間" %></td>
			<td><%= f.text_field :deliverytime %></td>
			<td><%= f.label :day, "曜日" %></td>
			<td><%= f.text_field :day %></td>
      <td></td>
      <td></td>
		</tr>
		<tr>
			<td><%= f.label :a, "時間時間内" %></td>
			<td><%= f.label :a, "会社名" %></td>
			<td><%= f.label :a, "部署名" %></td>
			<td><%= f.label :a, "氏名" %></td>
      <td><%= f.label :a, "Email" %></td>
      <td><%= f.label :a, "電話番号" %></td>
		</tr>
		<tr>
			<td><%= f.label :a, "1" %></td>
			<td><%= f.text_field :company2 %></td>
			<td><%= f.text_field :departmentname %></td>
			<td><%= f.text_field :name %></td>
      <td><%= f.text_field :email %></td>
      <td><%= f.text_field :phone %></td>
		</tr>
		<tr>
			<td><%= f.label :a, "2" %></td>
			<td><%= f.text_field :company3 %></td>
			<td><%= f.text_field :departmentname2 %></td>
			<td><%= f.text_field :name2 %></td>
      <td><%= f.text_field :email2 %></td>
      <td><%= f.text_field :phone2 %></td>
		</tr>
		<tr>
			<td><%= f.label :a, "3" %></td>
			<td><%= f.text_field :company4 %></td>
			<td><%= f.text_field :departmentname3 %></td>
			<td><%= f.text_field :name3 %></td>
      <td><%= f.text_field :email3 %></td>
      <td><%= f.text_field :phone3 %></td>
		</tr>
		<tr>
			<td><%= f.label :remark, "備考" %></td>
			<td colspan="7"><%= f.text_field :remark %></td>
		</tr>

	</table>
		</tbody>
		
		<div class="col-sm-12 row text-center">
		<%= f.submit '更新' , class: 'btn btn-default btn-left' %>
		<%= link_to "一覧に戻る", customers_path , class: 'btn btn-default btn-left' %>
    </div>
	<% end %>
</div>

app/views/customers/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><i class="#fa fa-search"></i> 検索条件</h3>
     </div>
      <div class="panel-body text-center">
         <%= form_tag(search_customers_path,:method => 'get') do %>
          <label class="control-label" for="">会社名</label>
     
                  <%= text_field_tag :search,'',size:50  , placeholder:"会社名を入力してください" %>
    
                  <%= link_to customers_path, class: 'btn btn-default btn-left' do %>Clear<% end %>
                  <%= submit_tag 'Search', :name => nil , class: 'btn btn-grey' %>
                  <% end %>
      </div>
    </div>
  </div>
</div>

app/views/customers/new.html.erb
<%= render 'form', customer: @customers %>

<style type="text/css">
.td_vertical_align_middle.td_vertical_align_middle {
  vertical-align: middle;
}
</style>

<%= form_for(@customers) do |f| %>
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><i class="#fa fa-search"></i> 会社登録</h3>
     </div>
       </div>
	<tbody>
	 <table class="table table-stripe table-bordere" >
		<tr>
			<td class="col-md-1"><%= f.label :company, "会社名" %></td>
 			<td class="col-md-3"><%= f.text_field :company %></td>
 			<td class="col-md-1"><%= f.label :vdc, "識別子" %></td>
 			<td class="col-md-2"><%= f.text_field :vdc , placeholder:"VDCの識別子" %></td>
 			<td class="col-md-1"><%= f.label :contractdate, "契約日" %></td>
 			<td class="col-md-2"><%= f.text_field :contractdate , placeholder:"yyyy/mm/dd" %></td>
		</tr>
		<tr>
			<td class="col-md-"><%= f.label :server, "監視プロダクト" %></td>
			<td "col-md-"><%= f.text_field :server %></td>
			<td "col-md-"><%= f.label :monitoring, "監視方法" %></td>
			<td><%= f.text_field :monitoring %></td>
			<td "col-md-"><%= f.label :cancellationdate, "解約日" %></td>
			<td><%= f.text_field :cancellationdate %></td>
		</tr>
		<tr>
			<td><%= f.label :product, "利用サービス" %></td>
			<td><%= f.text_field :product %></td>
			<td><%= f.label :level, "対応レベル" %></td>
			<td><%= f.text_field :level %></td>
      <td></td>
      <td></td>
		</tr>
		
		<tr>
			<td><%= f.label :a, "監視" %></td>
			<td><%= f.label :a, "URL" %></td>
			<td><%= f.label :a, "認証情報" %></td>
			<td><%= f.label :a, "IPアドレス" %></td>
      <td><%= f.label :a, "root" %></td>
      <td><%= f.label :a, "識別子" %></td>
		</tr>
		<tr>
			<td><%= f.label :a, "内部" %></td>
			<td><%= f.text_field :link %></td>
			<td><%= f.text_field :auth %></td>
			<td><%= f.text_field :ipadd %></td>
      <td><%= f.text_field :root %></td>
      <td><%= f.text_field :vdc2 %></td>
		</tr>
		<tr>
			<td><%= f.label :a, "外部" %></td>
			<td><%= f.text_field :link2 %></td>
			<td><%= f.text_field :auth2 %></td>
			<td><%= f.text_field :ipadd2 %></td>
      <td><%= f.text_field :root2 %></td>
      <td><%= f.text_field :vdc3 %></td>
		</tr>
		
		<tr>
			<td><%= f.label :sheet, "監視設定シート" %></td>
			<td><%= f.text_field :sheet %></td>
			<td></td>
			<td></td>
      <td></td>
      <td></td>
		</tr>
		

		
		
		
		<tr>
			<td><%= f.label :deliverytime, "提供時間" %></td>
			<td><%= f.text_field :deliverytime %></td>
			<td><%= f.label :day, "曜日" %></td>
			<td><%= f.text_field :day %></td>
      <td></td>
      <td></td>
		</tr>
		<tr>
			<td><%= f.label :a, "時間時間内" %></td>
			<td><%= f.label :a, "会社名" %></td>
			<td><%= f.label :a, "部署名" %></td>
			<td><%= f.label :a, "氏名" %></td>
      <td><%= f.label :a, "Email" %></td>
      <td><%= f.label :a, "電話番号" %></td>
		</tr>
		<tr>
			<td><%= f.label :a, "1" %></td>
			<td><%= f.text_field :company2 %></td>
			<td><%= f.text_field :departmentname %></td>
			<td><%= f.text_field :name %></td>
      <td><%= f.text_field :email %></td>
      <td><%= f.text_field :phone %></td>
		</tr>
		<tr>
			<td><%= f.label :a, "2" %></td>
			<td><%= f.text_field :company3 %></td>
			<td><%= f.text_field :departmentname2 %></td>
			<td><%= f.text_field :name2 %></td>
      <td><%= f.text_field :email2 %></td>
      <td><%= f.text_field :phone2 %></td>
		</tr>
		<tr>
			<td><%= f.label :a, "3" %></td>
			<td><%= f.text_field :company4 %></td>
			<td><%= f.text_field :departmentname3 %></td>
			<td><%= f.text_field :name3 %></td>
      <td><%= f.text_field :email3 %></td>
      <td><%= f.text_field :phone3 %></td>
		</tr>
		<tr>
			<td><%= f.label :remark, "備考" %></td>
			<td colspan="7"><%= f.text_field :remark %></td>
		</tr>

	</table>
		</tbody>
		
		<div class="col-sm-12 row text-center">
		<%= f.submit '登録' , class: 'btn btn-default btn-left' %>
		<%= link_to "検索画面に戻る", customers_path , class: 'btn btn-default btn-left' %>
    </div>
	<% end %>
</div>

app/views/customers/search.html.bk.erb
<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><i class="#fa fa-search"></i> 会社情報</h3>
     </div>
      <div class="panel-body">
       <%# if @customers %>
        <% @customers.each do |customer| %>
         <div class="row">
           <div class="col-sm-6">
               <!-- 会社名 -->
               <div class="form-group">
                <label class="col-sm-4 control-label" for="">会社名</label>
                <div class="col-sm-8"><%= link_to customer.id, customer %> : <%= customer.company %>
                </div>
               </div>
               
               <!-- 電話番号 -->
               <div class="form-group">
                <label class="col-sm-4 control-label" for="">電話番号</label>
                <div class="col-sm-8"><%= customer.phone %>
                </div>
               </div>
           </div>
           
           <div class="col-sm-6">
               <!-- サーバ -->
               <div class="form-group">
                <label class="col-sm-4 control-label" for="">サーバ</label>
                <div class="col-sm-8"><%= customer.server %>
                </div>
               </div>
             
               <!-- 備考 -->
               <div class="form-group">
                <label class="col-sm-4 control-label" for="">備考</label>
                <div class="col-sm-8"><%= customer.remark %>
                </div>
               </div>         
           </div>
          </div>
         <% end %>
       <%# end %>
      </div>
      
      <div class="col-sm-12 row text-center">
      <%= link_to "csv出力", csv_output_customers_path(customer_ids: @customers.pluck(:id), format: :csv) , class: 'btn btn-default btn-left' %>
      <%= link_to "検索画面に戻る", customers_path , class: 'btn btn-default btn-left' %>
      </div>


<% 
=begin 
%>
<% if @customers %>
  <% @customers.each do |customer| %>
     <li><%= link_to customer.id, customer %> : <%= customer.company %></li>
     <li><%= customer.phone %></li>
     <li><%= customer.server %></li>
     <li><%= customer.remark %></li>
  <% end %>
<% end %>
<%
=end
%>




<% 
=begin 
%>
複数行コメント
<% if @customers %>
  <% @customers.each do |customer| %>
     <li><%= link_to customer.id, customer %> : <%= customer.company %></li>
     <li><%= customer.phone %></li>
     <li><%= customer.server %></li>
     <li><%= customer.remark %></li>
  <% end %>
<% end %>

<%
=end
%>

app/views/customers/search.html.erb
<style type="text/css">
.td_vertical_align_middle.td_vertical_align_middle {
  vertical-align: middle;
}
</style>


<div class="panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title"><i class="#fa fa-search"></i> 会社情報</h3>
     </div>
       </div>

	<tbody>
 <% @customers.each do |customer| %>
	 <table class="table table-striped table-bordered" >
		<tr>
			 <td rowspan="15" class="col-md-1 td_vertical_align_middle" style="" align="center">
			  <%#= link_to customer.id, customer %>
     <% if can? :edit, @customer %>
        <%= link_to customer.id, customer %>
     <% else %>
        <%= customer.id %>
     <% end %>
			 </td>
			 <td class="col-md-1">会社名</td>
 			<td class="col-md-3"><%= customer.company %></td>
 			<td class="col-md-1">識別子</td>
 			<td class="col-md-2"><%= customer.vdc %></td>
 			<td class="col-md-1">契約日</td>
 			<td class="col-md-2"><%= customer.contractdate %></td>
		</tr>
		<tr>
			<td class="col-md-">監視プロダクト </td>
			<td "col-md-"><%= customer.server %></td>
			<td "col-md-">監視方法</td>
			<td><%= customer.monitoring %></td>
			<td "col-md-">解約日</td>
			<td><%= customer.cancellationdate %></td>
		</tr>
		<tr>
			<td>利用サービス</td>
			<td><%= customer.product %></td>
			<td>対応レベル</td>
			<td><%= customer.level %></td>
   <td>更新日</td>
   <td><%= customer.updated_at.strftime("%Y-%m-%d %H:%M") %></td>
		</tr>
		

		<tr>
			<td><p>監視</p></td>
			<td><p>URL</p></td>
			<td><p>認証情報</p></td>
			<td><p>IPアドレス</p></td>
            <td><p>root</p></td>
            <td><p>識別子</p></td>
		</tr>
		<tr>
			<td><p>内部</p></td>
			<td><%= customer.link %></td>
			<td><%= customer.auth %></td>
			<td><%= customer.ipadd %></td>
      <td><%= customer.root %></td>
      <td><%= customer.vdc2 %></td>
		</tr>
		<tr>
			<td><p>外部</p></td>
			<td><%= customer.link2 %></td>
			<td><%= customer.auth2 %></td>
			<td><%= customer.ipadd2 %></td>
			<td><%= customer.root2 %></td>
　　　<td><%= customer.vdc3 %></td>
		</tr>
		
		
		<tr>
			<td>監視設定シート</td>
			<td colspan="7"><%= customer.sheet %></td>
		</tr>
		<tr>
			<td>監視提供時間</td>
			<td><%= customer.deliverytime %></td>
			<td>曜日</td>
			<td><%= customer.day %></td>
   <td colspan="4"></td>
		</tr>
		<tr>
			<td colspan="">営業時間内</td>
			<td>会社名</td>
			<td>部署名</td>
			<td>氏名</td>
   <td>Email</td>
   <td>電話番号</td>
		</tr>
		<tr>
			<td colspan="">1</td>
			<td><%= customer.company2 %></td>
			<td><%= customer.departmentname %></td>
			<td><%= customer.name %></td>
   <td><%= customer.email %></td>
   <td><%= customer.phone %></td>
		</tr>
		<tr>
			<td colspan="">2</td>
			<td><%= customer.company3 %></td>
			<td><%= customer.departmentname2 %></td>
			<td><%= customer.name2 %></td>
   <td><%= customer.email2 %></td>
   <td><%= customer.phone2 %></td>
		</tr>
		<tr>
			<td colspan="">3</td>
			<td><%= customer.company4 %></td>
			<td><%= customer.departmentname3 %></td>
			<td><%= customer.name3 %></td>
   <td><%= customer.email3 %></td>
   <td><%= customer.phone3 %></td>
		</tr>
		<tr>
			<td>備考</td>  
			<td colspan="7"><%= customer.remark %></td>
		</tr>
	</table>
		</tbody>
	<% end %>
</div>

<div class="col-sm-12 row text-center">
<%= link_to "csv出力", csv_output_customers_path(customer_ids: @customers.pluck(:id), format: :csv) , class: 'btn btn-default btn-left' %>
<%= link_to "検索画面に戻る", customers_path , class: 'btn btn-default btn-left' %>
</div>

app/views/customers/show.html.erb
<style type="text/css">
.td_vertical_align_middle.td_vertical_align_middle {
 vertical-align: middle;
}
</style>

<div class="panel panel-default">
 <div class="panel-heading">
 <h3 class="panel-title"><i class="#fa fa-search"></i> 登録詳細：<%= @customers.id %> </h3>
 </div>
</div>

<tbody>
	<table class="table table-stripe table-bordere" >
		<tr>
			<td class="col-md-1"><p>会社名</p></td>
 			<td class="col-md-3"><%= @customers.company %></td>
 			<td class="col-md-1"><p>識別子</p></td>
 			<td class="col-md-2"><%= @customers.vdc %></td>
 			<td class="col-md-1"><p>契約日</p></td>
 			<td class="col-md-2"><%= @customers.contractdate %></td>
		</tr>
		<tr>
			<td class="col-md-"><p>監視プロダクト</p></td>
			<td "col-md-"><%= @customers.server %></td>
			<td "col-md-"><p>監視方法</p></td>
			<td><%= @customers.monitoring %></td>
			<td "col-md-"><p>解約日</p></td>
			<td><%= @customers.cancellationdate %></td>
		</tr>
		<tr>
			<td><p>利用サービス</p></td>
			<td><%= @customers.product %></td>
			<td><p>対応レベル</p></td>
			<td><%= @customers.level %></td>
			<td></td>
			<td></td>
		</tr>
		
		<tr>
			<td><p>監視</p></td>
			<td><p>URL</p></td>
			<td><p>認証情報</p></td>
			<td><p>IPアドレス</p></td>
            <td><p>root</p></td>
            <td><p>識別子</p></td>
		</tr>
		<tr>
			<td><p>内部</p></td>
			<td><%= @customers.link %></td>
			<td><%= @customers.auth %></td>
			<td><%= @customers.ipadd %></td>
            <td><%= @customers.root %></td>
            <td><%= @customers.vdc2 %></td>
		</tr>
		<tr>
			<td><p>外部</p></td>
			<td><%= @customers.link2 %></td>
			<td><%= @customers.auth2 %></td>
			<td><%= @customers.ipadd2 %></td>
			<td><%= @customers.root2 %></td>
　　　　　　<td><%= @customers.vdc3 %></td>
		</tr>
		
		<tr>
			<td><p>登録シート</p></td>
			<td><%= @customers.sheet %></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td><p>提供時間</p></td>
			<td><%= @customers.deliverytime %></td>
			<td><p>曜日</p></td>
			<td><%= @customers.day %></td>
			<td></td>
			<td></td>
		</tr>
		<tr>
			<td><p>営業時間内</p></td>
			<td><p>会社名</p></td>
			<td><p>部署名</p></td>
			<td><p>氏名</p></td>
			<td><p>Email</p></td>
			<td><p>電話番号</p></td>
		</tr>
		<tr>
			<td><p>1</p></td>
			<td><%= @customers.company2 %></td>
			<td><%= @customers.departmentname %></td>
			<td><%= @customers.name %></td>
			<td><%= @customers.email %></td>
			<td><%= @customers.phone %></td>
		</tr>
		<tr>
			<td><p>2</p></td>
			<td><%= @customers.company3 %></td>
			<td><%= @customers.departmentname2 %></td>
			<td><%= @customers.name2 %></td>
			<td><%= @customers.email2 %></td>
			<td><%= @customers.phone2 %></td>
		</tr>
		<tr>
			<td><p>3</p></td>
			<td><%= @customers.company4 %></td>
			<td><%= @customers.departmentname3 %></td>
			<td><%= @customers.name3 %></td>
			<td><%= @customers.email3 %></td>
			<td><%= @customers.phone3 %></td>
		</tr>
		<tr>
			<td><p>備考</p></td>
			<td colspan="7"><%= @customers.remark %></td>
		</tr>
		<tr>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
			<td></td>
		</tr>
	 </table>
 </tbody>

<div class="col-sm-12 row text-center">
<%= link_to "一覧に戻る", customers_path , class: 'btn btn-default btn-left' %>
<%= link_to "この登録内容を編集する", edit_customer_path(@customers) , class: 'btn btn-default btn-left' %>
<%= link_to "このメッセージを削除する", @customers, method: :delete, data: { confirm: "本当に削除してよろしいですか？" } , class: 'btn btn-default btn-left' %>
</div>






<% 
=begin 
%>
<h1>id: <%= @customers.id %> の詳細ページ</h1>

<p>会社名：<%= @customers.company %></p>
<p>識別子：<%= @customers.vdc %></p>
<p>契約日：<%= @customers.contractdate %></p>
<p>監視プロダクト：<%= @customers.server %></p>
<p>監視方法：<%= @customers.monitoring %></p>
<%
=end
%>

app/views/layouts/_flash_customers.html.erb
<% flash.each do |customer_type, customer| %>
  <div class="alert alert-<%= customer_type %>">
    <%= customer %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-default navbar-static-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">CustomerDB</a>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">
         <% if can? :new, @customer %>
          <li><%= link_to  'Signup', new_customer_path %></li>
          <%#= link_to  'Signup', new_customer_path %>
          <% else %>
           <li></li>
         <% end %>
            
         <% if user_signed_in? %>
         <li><%= link_to "Logout", destroy_user_session_path, method: :delete  %></li>
         <% else %>
         <li><%= link_to "Login", new_user_session_path %></li>
         <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- # レスポンシブデザイン -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    
    <title>CustomerDB</title>
    <%= csrf_meta_tags %>
    
    <!-- # Bootstrap CDN -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    


    
    <%= render 'layouts/navbar' %>
    
    
    <div class="container">
      <!-- # flashメッセージ -->
      <%= render 'layouts/flash_customers' %>
      
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/top/index.html.erb
<% if user_signed_in? %>


<%= render template: 'customers/index' %>

<%#= link_to "Logout", destroy_user_session_path, method: :delete , class: 'btn btn-lg btn-primary' %>

<% else %>

<div class="center jumbotron">
  <div class="text-center">
    <h1>CustomerDB</h1>
  </div>
</div>
 
    <%# if user_signed_in? %>
    <%#= link_to "Logout", destroy_user_session_path, method: :delete , class: 'btn btn-lg btn-primary' %>
<%# else %>
    <%#= link_to "Login", new_user_session_path, class: 'btn btn-lg btn-primary'%>
    
<%# end %>
      <!-- # flashメッセージtest -->
<p class="notice"><%#= notice %></p>
<p class="alert"><%#= alert %></p>

<% end %>